Update pre-push

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,6 +1,19 @@
 #!/bin/sh
+# From gist at https://gist.github.com/chadmaughan/5889802
 
+echo '[git hook] executing gradle spotlessCheck before commit'
 
-gradle spotlessCheck
-if [ $? -ne 0 ]; then exit 1; fi
-exit 0
+# stash any unstaged changes
+git stash -q --keep-index
+
+# run the spotlessCheck with the gradle wrapper
+./gradlew spotlessCheck --daemon
+
+# store the last exit code in a variable
+RESULT=$?
+
+# unstash the unstashed changes
+git stash pop -q
+
+# return the './gradlew spotlessCheck' exit code
+exit $RESULT
